"""
Distinct Powers: How many distinct terms are in the sequence generated by a^b
for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
"""

def distPowers():
    s = {0, 1}
    for a in range(2, 101):
        for b in range(2, 101):
            s.add(pow(a, b))
    return len(s) - 2
